/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/Maze.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Maze({props}) {
  const { nodes, materials } = useGLTF('/models/Maze.glb');

  const initialZ = 0.5;

  return (
      <group {...props} dispose={null}>

          <group>
          <mesh geometry={nodes.group1339938539.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group888081882.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1696790337.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group684641087.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1923253327.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1435604739.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group627163454.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group312270577.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1486264385.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1835987345.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group2097294060.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1015650822.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group877405770.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group143819141.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1420049182.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1917735983.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group538700523.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1904138473.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group242609474.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group2105293899.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group2031629934.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1301129089.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group902521578.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group389333068.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1518418431.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1498641121.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1739093882.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1076364528.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1301220202.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group905411319.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group927986261.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group164752539.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1927863357.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1350365362.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1831306961.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1509008425.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1615018172.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1999875301.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group954241638.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1805490621.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1223501175.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1483823549.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group276816887.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group209971307.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group306870740.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group334839597.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group2098247374.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group923493655.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group956561248.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1959201001.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group202375474.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1758500788.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1655225029.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1918454941.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group415541115.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group2126511570.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1503225792.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group347147352.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group447917265.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1323964242.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group1674194485.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group747653310.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group678286359.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group744571175.geometry} material={materials.mat21}/>
          <mesh geometry={nodes.group2121271720.geometry} material={materials.mat21}/>
          </group>

          <group position={[0,0.1,0]}>
              <mesh scale={0.1} position={[0.1, 0, 0.1]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#e15050"}/>
              </mesh>
              <mesh scale={0.1} position={[0.5, 0, 0.35]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#e15050"}/>
              </mesh>
              <mesh scale={0.1} position={[-0.5, 0, 0.35]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#e15050"}/>
              </mesh>
              <mesh scale={0.1} position={[-0.5, 0, 1]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#e15050"}/>
              </mesh>
          </group>

          <group position={[0,0.1,0]}>
              <mesh scale={0.1} position={[0.1, 0, -1]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#5fe150"}/>
              </mesh>
              <mesh scale={0.1} position={[0.9, 0, -1]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#5fe150"}/>
              </mesh>
              <mesh scale={0.1} position={[1, 0, 0.35]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#5fe150"}/>
              </mesh>
              <mesh scale={0.1} position={[-0.6, 0, -0.8]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#5fe150"}/>
              </mesh>
              <mesh scale={0.1} position={[0.5, 0, 1]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#5fe150"}/>
              </mesh>
          </group>

          <group position={[0,0.1,0]}>
              <mesh scale={0.1} position={[0.4, 0, -0.6]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#5068e1"}/>
              </mesh>
              <mesh scale={0.1} position={[0.6, 0, -0,8]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#5068e1"}/>
              </mesh>
              <mesh scale={0.1} position={[1, 0, 1]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#5068e1"}/>
              </mesh>
              <mesh scale={0.1} position={[-1, 0, -1]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#5068e1"}/>
              </mesh>
              <mesh scale={0.1} position={[-1, 0, 1]}>
                  <boxGeometry/>
                  <meshBasicMaterial color={"#5068e1"}/>
              </mesh>
          </group>
      </group>
  )
}

useGLTF.preload('/models/Maze.glb')
